pkgix: Add support for listing dependencies with version information
Packages can now list dependencies in the `depends` field, with
additional version information: <dependency>(>|<|>=|<=|=)<ver>

This helps to ensure that the correct package versions are installed.
This just checks against either already installed packages or checks
against dependencies installed by a target.

This should not be confused with installing packages of a specific
version, by simply providing a package file with the version encoded in
the name. It would be difficult to guess and resolve version issues
without the user specifying which package exactly provides required
version. Such packages would then need to provide an entry in the
`provides` field with the basename of the package.

Signed-off-by: Marco Elver <me@marcoelver.com>

diff --git a/bin/pkgix b/bin/pkgix
--- a/bin/pkgix
+++ b/bin/pkgix
@@ -347,7 +347,7 @@ elif type -p md5 > /dev/null; then
 		fi
 	}
 else
-	warning_printf $"No suitable MD5 command found; MD5 checksums not supported."
+	warning_printf $"No suitable MD5 command found; MD5 checksums not supported.\n"
 fi
 
 case "$(uname -s)" in
@@ -585,7 +585,7 @@ remove_invalid_symlinks() { #{{{
 
 	find "$path" "${find_args[@]:+${find_args[@]}}" -type l |
 	while read lpath; do
-		[[ ! -e "$lpath" ]] && rm -v "$lpath" || :
+		[[ ! -e "$lpath" ]] && rm "$lpath" || :
 	done
 } #}}}
 
@@ -940,14 +940,54 @@ unset_sourced_pkg() { #{{{
 } #}}}
 
 #============================================================================
-# pkg_db_isinstalled pkgix_prefix pkg_name
+# pkg_db_isinstalled pkgix_prefix pkg_name [compare_version]
+# If compare_version is provided, in the format of:
+# ("<="|">="|"<"|">"|"=")<version>
+# then a bash string comparison (sorted lexicographically) will be performed.
 #
 pkg_db_isinstalled() { #{{{
 	local pkgix_prefix="$1"
 	local pkg_name="$2"
+	local compare_version="${3:-}"
 	local db_prefix_pkg="${pkgix_prefix}/${DB_PREFIX}/${pkg_name}"
 
-	[[ -f "${db_prefix_pkg}/version" && -f "${db_prefix_pkg}/files" ]]
+	if [[ -f "${db_prefix_pkg}/version" && -f "${db_prefix_pkg}/files" ]]; then
+		if [[ -n "$compare_version" ]]; then
+			local lhs="$(<"${db_prefix_pkg}/version")"
+			case "$compare_version" in
+				"<="*)
+					[[ "$lhs" == "${compare_version##<=}" || "$lhs" < "${compare_version##<=}" ]] \
+						&& return $RET_OK \
+						|| return $RET_ERR
+					;;
+				">="*)
+					[[ "$lhs" == "${compare_version##>=}" || "$lhs" > "${compare_version##>=}" ]] \
+						&& return $RET_OK \
+						|| return $RET_ERR
+					;;
+				"<"*)
+					[[ "$lhs" < "${compare_version##<}" ]] \
+						&& return $RET_OK \
+						|| return $RET_ERR
+					;;
+				">"*)
+					[[ "$lhs" > "${compare_version##>}" ]] \
+						&& return $RET_OK \
+						|| return $RET_ERR
+					;;
+				"="*)
+					[[ "$lhs" == "${compare_version##=}" ]] \
+						&& return $RET_OK \
+						|| return $RET_ERR
+					;;
+				*) die ;;
+			esac
+		else
+			return $RET_OK
+		fi
+	fi
+
+	return $RET_ERR
 } #}}}
 
 #============================================================================
@@ -1236,9 +1276,28 @@ pkg_install() { #{{{
 
 		if (( ! arg_nodeps )); then
 			msg_printf "${Cgrn}%s (%s)${Crst} "$"resolving dependencies...\n" "$pkg_name" "${version:-}"
+			local dep_name_ver
 			local dep_name
-			for dep_name in "${depends[@]:+${depends[@]}}"; do
+			local dep_version
+			for dep_name_ver in "${depends[@]:+${depends[@]}}"; do
+				dep_name="${dep_name_ver%%[<>=]*}"
+				dep_version="${dep_name_ver##${dep_name}}"
+
+				if [[ -n "$dep_version" ]] && pkg_db_isinstalled "$pkgix_prefix" "$dep_name" \
+					  && ! pkg_db_isinstalled "$pkgix_prefix" "$dep_name" "$dep_version"; then
+					# Package is installed, but the required version is not
+					# available; let the user sort it out.
+					die $"Package dependency could not be resolved: %s (installed: %s)\n" \
+						"$dep_name_ver" "$(pkg_db_info_query "$pkgix_prefix" "$dep_name" "version")"
+				fi
+
 				pkg_install "$pkgix_prefix" "$dep_name" 0 "$REASON_DEPENDENCY"
+
+				if (( ! arg_dry_run )) && [[ -n "$dep_version" ]] \
+					&& ! pkg_db_isinstalled "$pkgix_prefix" "$dep_name" "$dep_version"; then
+					warning_printf $"Package dependency not fully resolved: %s (installed: %s)\n" \
+						"$dep_name_ver" "$(pkg_db_info_query "$pkgix_prefix" "$dep_name" "version")"
+				fi
 			done
 		else
 			warning_printf $"Ignoring dependencies.\n"
@@ -1720,10 +1779,14 @@ cmd_list() { #{{{
 								# Tried using grep here, but the BASH-only
 								# version is roughly 2x faster.
 								source "$db_info_file"
-								if in_list "$pkg_name" "${depends[@]:+${depends[@]}}"; then
-									verbose_printf $"'%s: %s' required by '%s: %s'\n" "$pkgix_prefix" "$pkg_name" "$_pkgix_prefix" "$_pkg_name"
-									exit $EXIT_ERR
-								fi
+								local dep_name_ver
+								for dep_name_ver in "${depends[@]:+${depends[@]}}"; do
+									if [[ "$pkg_name" == "${dep_name_ver%%[<>=]*}" ]]; then
+										verbose_printf $"'%s: %s' required by '%s: %s'\n" \
+											"$pkgix_prefix" "$pkg_name" "$_pkgix_prefix" "$_pkg_name"
+										exit $EXIT_ERR
+									fi
+								done
 							done || exit $?
 						done
 					) || continue
