pkgix: Display error in all cases where a dependency can not be satisfied
Simplify post-dependency installation dependency check. This change was
made primarily, so that a dependency which was pulled but does not
satisfy the right version, would result in an error instead of a
warning.

Signed-off-by: Marco Elver <me@marcoelver.com>

diff --git a/bin/pkgix b/bin/pkgix
--- a/bin/pkgix
+++ b/bin/pkgix
@@ -1245,17 +1245,17 @@ db_info_query() { #{{{
 	fi
 
 	(
-		local result
+		local result=""
 
 		set_db_vars "$pkgix_prefix" "$pkg_name" || :
 
 		case "$property" in
 			version)
-				result="$(<"$db_version_file")"
+				[[ -f "$db_version_file" ]] && result="$(<"$db_version_file")" || :
 				[[ -z "$result" ]] && echo "$default" || echo "$result"
 				;;
 			*)
-				source "$db_info_file"
+				[[ -f "$db_info_file" ]] && source "$db_info_file" || :
 				echo "${!property:-${default}}"
 				unset_db_info
 				;;
@@ -1437,20 +1437,13 @@ pkg_install() { #{{{
 				dep_name="${dep_name_ver%%[<>=]*}"
 				dep_cmp_version="${dep_name_ver##${dep_name}}"
 
-				if [[ -n "$dep_cmp_version" ]] && db_isinstalled "$pkgix_prefix" "$dep_name" \
-					  && ! db_isinstalled "$pkgix_prefix" "$dep_name" "$dep_cmp_version"; then
-					# Package is installed, but the required version is not
-					# available; let the user sort it out.
-					die $"Package dependency could not be resolved: %s (installed: %s)\n" \
-						"$dep_name_ver" "$(db_info_query "$pkgix_prefix" "$dep_name" "version")"
-				fi
-
 				pkg_install "$pkgix_prefix" "$dep_name" 0 "$REASON_DEPENDENCY"
 
-				if [[ -n "$dep_cmp_version" ]] \
-					&& ! db_isinstalled "$pkgix_prefix" "$dep_name" "$dep_cmp_version"; then
-					warning_printf $"Package dependency not fully resolved: %s (installed: %s)\n" \
-						"$dep_name_ver" "$(db_info_query "$pkgix_prefix" "$dep_name" "version")"
+				if ! db_isinstalled "$pkgix_prefix" "$dep_name" "$dep_cmp_version"; then
+					# Either package is not installed, in which case something went horribly
+					# wrong, or the package is installed but the required version is not.
+					die $"Package dependency could not be resolved: %s (installed: %s)\n" \
+						"$dep_name_ver" "$(db_info_query "$pkgix_prefix" "$dep_name" "version" "None")"
 				fi
 			done
 		else
@@ -1755,13 +1748,13 @@ prefix_upgrade() { #{{{
 					pkg_install "$pkgix_prefix" "$pkg_name" 1
 				fi
 			else
-				msg_printf "%s (%s) "$"is up to date\n" "$pkg_name" "$old_version"
+				verbose_printf "${CcynB}=> %s (%s)${Crst} "$"is up to date\n" "$pkg_name" "$old_version"
 			fi
 		) || exit $?  # Break out of pipe-subshell
 	done || {	unlock_prefix "$pkgix_prefix" ;
 				return $? ; } # Take return code if pipe-subshell exited with errors
 
-	msg_printf $"Done upgrading.\n"
+	msg_printf $"done upgrading.\n"
 
 	unlock_prefix "$pkgix_prefix"
 
